import type { FormEvent } from "react";
import type { AgentConfig, Conversation, ConversationSummary, MemoryItem, MemoryState, ModelConfig, ModelProviderConfig, RoleStore, WebSearchResponse } from "./types";

export type ActivePanel = "search" | "settings" | "memory" | "tools" | "summary" | "agent" | "webSearch" | null;
export type ChatMode = "normal" | "thinking" | "memory" | "tools" | "web";
export type PanelPhase = "enter" | "exit";
export type BusyAction = "model-test" | "memory-commit" | "memory-organize" | "web-search" | "role-save" | "conversation-switch" | null;

export interface WorkbenchProps {
  agentConfig: AgentConfig;
  roleStore: RoleStore;
  modelConfig: ModelConfig;
  selectedProvider: ModelProviderConfig;
  conversation: Conversation;
  conversations: ConversationSummary[];
  memoryState: MemoryState;
  pendingCandidates: MemoryItem[];
  draft: string;
  saving: boolean;
  sending: boolean;
  status: string;
  error: string;
  adminToken: string;
  activePanel: ActivePanel;
  renderedPanel: ActivePanel;
  panelPhase: PanelPhase;
  activeMode: ChatMode;
  generatedSummary: string;
  webSearchState: WebSearchResponse | null;
  busyAction: BusyAction;
  statusKey: number;
  memoryFeedbackKey: number;
  memoryPanelCollapsed: boolean;
  setDraft: (value: string) => void;
  updateAdminToken: (value: string) => void;
  updateAgent: (config: AgentConfig) => Promise<void>;
  createRole: (role: Partial<AgentConfig>) => Promise<void>;
  deleteRole: (roleId: string) => Promise<void>;
  selectRole: (roleId: string) => Promise<void>;
  saveModel: (config: ModelConfig) => Promise<boolean>;
  testModel: () => Promise<void>;
  sendMessage: (event?: FormEvent) => Promise<void>;
  commitCandidates: (items?: MemoryItem[]) => Promise<void>;
  updateMemoryItem: (memoryId: string, patch: Partial<MemoryItem>) => Promise<void>;
  deleteMemoryItem: (memoryId: string) => Promise<void>;
  rejectMemoryItem: (memoryId: string) => Promise<void>;
  editMemoryItem: (item: MemoryItem) => Promise<void>;
  organizeMemory: () => Promise<void>;
  runWebSearch: (query: string) => Promise<WebSearchResponse | null>;
  setMobileView: (view: "chat" | "settings") => void;
  openPanel: (panel: Exclude<ActivePanel, null>, message?: string) => void;
  closePanel: () => void;
  chooseMode: (mode: ChatMode) => void;
  generateSummary: () => void;
  saveSummaryCandidate: () => void;
  handleAttachment: () => void;
  handleVoice: () => void;
  notify: (message: string) => void;
  createConversation: (options?: { title?: string; roleId?: string }) => Promise<void>;
  switchConversation: (conversationId: string) => Promise<void>;
  deleteConversation: (conversationId: string) => Promise<void>;
  setConversationRole: (roleId: string) => Promise<void>;
  toggleMemoryPanel: () => void;
}
