import type { FormEvent } from "react";
import type { AgentConfig, AgentTask, AgentTool, Conversation, ConversationSearchResult, ConversationSummary, ExpertTeam, ExpertTeamStore, MemoryItem, MemoryState, ModelConfig, ModelProviderConfig, RoleStore, WebSearchResponse } from "./types";

export type ActivePanel = "search" | "settings" | "memory" | "tools" | "summary" | "agent" | "webSearch" | "team" | null;
export type ChatMode = "normal" | "thinking" | "memory" | "tools" | "web";
export type PanelPhase = "enter" | "exit";
export type BusyAction = "model-test" | "memory-commit" | "memory-organize" | "web-search" | "tool-run" | "role-save" | "team-save" | "conversation-switch" | "conversation-update" | null;

export interface WorkbenchProps {
  agentConfig: AgentConfig;
  roleStore: RoleStore;
  teamStore: ExpertTeamStore;
  modelConfig: ModelConfig;
  selectedProvider: ModelProviderConfig;
  conversation: Conversation;
  conversations: ConversationSummary[];
  memoryState: MemoryState;
  pendingCandidates: MemoryItem[];
  draft: string;
  saving: boolean;
  sending: boolean;
  hasStarted: boolean;
  status: string;
  error: string;
  adminToken: string;
  activePanel: ActivePanel;
  renderedPanel: ActivePanel;
  panelPhase: PanelPhase;
  activeMode: ChatMode;
  generatedSummary: string;
  webSearchState: WebSearchResponse | null;
  tools: AgentTool[];
  tasks: AgentTask[];
  workspaceRoot: string;
  busyAction: BusyAction;
  statusKey: number;
  memoryFeedbackKey: number;
  memoryPanelCollapsed: boolean;
  setDraft: (value: string) => void;
  updateAdminToken: (value: string) => void;
  updateAgent: (config: AgentConfig) => Promise<void>;
  uploadRoleBackground: (file: File) => Promise<void>;
  resetRoleBackground: () => Promise<void>;
  createRole: (role: Partial<AgentConfig>) => Promise<void>;
  deleteRole: (roleId: string) => Promise<void>;
  selectRole: (roleId: string) => Promise<void>;
  createTeam: (team: Pick<ExpertTeam, "name" | "goal" | "enabled" | "leadRoleId" | "memberRoleIds">) => Promise<void>;
  updateTeam: (teamId: string, team: Pick<ExpertTeam, "name" | "goal" | "enabled" | "leadRoleId" | "memberRoleIds">) => Promise<void>;
  selectTeam: (teamId: string) => Promise<void>;
  deleteTeam: (teamId: string) => Promise<void>;
  saveModel: (config: ModelConfig) => Promise<boolean>;
  testModel: () => Promise<void>;
  sendMessage: (event?: FormEvent) => Promise<void>;
  commitCandidates: (items?: MemoryItem[]) => Promise<void>;
  updateMemoryItem: (memoryId: string, patch: Partial<MemoryItem>) => Promise<void>;
  deleteMemoryItem: (memoryId: string) => Promise<void>;
  rejectMemoryItem: (memoryId: string) => Promise<void>;
  editMemoryItem: (item: MemoryItem) => Promise<void>;
  organizeMemory: () => Promise<void>;
  runWebSearch: (query: string) => Promise<WebSearchResponse | null>;
  runTool: (toolId: string, objective: string, input: Record<string, unknown>) => Promise<AgentTask | null>;
  approveTask: (taskId: string) => Promise<AgentTask | null>;
  cancelTask: (taskId: string) => Promise<AgentTask | null>;
  setMobileView: (view: "chat" | "settings") => void;
  openPanel: (panel: Exclude<ActivePanel, null>, message?: string) => void;
  closePanel: () => void;
  chooseMode: (mode: ChatMode) => void;
  generateSummary: () => void;
  saveSummaryCandidate: () => void;
  handleAttachment: () => void;
  handleVoice: () => void;
  notify: (message: string) => void;
  createConversation: (options?: { title?: string; roleId?: string }) => Promise<void>;
  switchConversation: (conversationId: string) => Promise<void>;
  deleteConversation: (conversationId: string) => Promise<void>;
  renameConversation: (conversationId: string, title: string) => Promise<void>;
  toggleConversationStarred: (conversationId: string, starred: boolean) => Promise<void>;
  exportConversation: (conversationId: string, format?: "markdown" | "txt" | "json") => Promise<void>;
  searchConversations: (query: string) => Promise<ConversationSearchResult[]>;
  setConversationRole: (roleId: string) => Promise<void>;
  regenerateMessage: () => Promise<void>;
  copyMessage: (content: string) => Promise<void>;
  isRegenerating: boolean;
  toggleMemoryPanel: () => void;
}
